In [1]:
import os
import json
from pprint import pprint
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from operator import is_not
from functools import partial
import math
import re
#load our cutomized data load module
import loaddata

In [2]:
#this code read files under two folder and merge them together into one data frame
#1 Read mojo files
mojo_data = loaddata.load_mojo_data()
mojo_df = pd.DataFrame(mojo_data)
mojo_df['title_clean'] = mojo_df['title'].str.replace('[^\w]','').str.lower()
#2 Read meta files
meta_data = loaddata.load_metacritic_data()
meta_df = pd.DataFrame(meta_data)
meta_df['title_clean'] = meta_df['title'].str.replace('[^\w]','').str.lower()
#3 Merge two file together
df_merged = pd.merge(mojo_df, 
                     meta_df,
                     on='title_clean',
                     how = 'left')
# check the final data frame
df_merged.head()

Parsed 3728 movies from 3728 files
Parsed 4765 metacritic files from 4767 files

,alt_title,director_x,domestic_gross,mojo_slug,opening_per_theater,opening_weekend_take,production_budget,release_date_limited,release_date_wide,title_x,...,num_user_ratings,num_user_reviews,rating,release_date,runtime_minutes,studio,title_y,unable to retrieve,user_score,year_y
0,"10,000 B.C. (2008)",Roland Emmerich,94784201.0,10000bc,10518.0,35867488.0,105000000.0,None,2008-03-07,"10,000 B.C.",...,273.0,"50, 18, 60, 128",PG-13,2008-03-07,109.0,Warner Bros. Pictures,"10,000 BC",NaN,4.6,2008
1,102 Dalmatians (2000),None,66957026.0,102dalmatians,7353.0,19883351.0,85000000.0,None,2000-11-22,102 Dalmatians,...,47.0,"7, 3, 3, 13",G,2000-11-22,100.0,Buena Vista Pictures,102 Dalmatians,NaN,5.3,2000
2,10 Things I Hate About You (1999),None,38178166.0,10thingsihateaboutyou,3668.0,8330681.0,30000000.0,None,1999-03-31,10 Things I Hate About You,...,175.0,"27, 1, 1, 29",PG-13,1999-03-31,97.0,Buena Vista Pictures,10 Things I Hate About You,NaN,7,1999
3,10 Years (2012),Jamie Linden,203373.0,10years,7569.0,22707.0,NaN,None,2012-09-14,10 Years,...,12.0,"3, 2, 1, 6",R,2012-09-14,100.0,Anchor Bay Entertainment,10 Years,NaN,6.6,2012
4,11 Flowers (2013),None,9213.0,11flowers,1758.0,3516.0,NaN,None,2013-02-22,11 Flowers,...,NaN,"1, 0, 0, 1",Not Rated,2013-02-22,110.0,First Run Features,11 Flowers,NaN,tbd,2013

In [7]:
# check the final data frame
df_merged[,0:10]

SyntaxError: invalid syntax (<ipython-input-7-383f143face5>, line 2)